matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd host
      install:
        - pip install -r host/requirements.txt
      script:
        - pytest
    - language: node_js
      node_js:
        - 10.3
      before_install:
        - cd guest
      install:
        - npm install
      script:
        - npm test

notifications:
  email: false